name: Update Cloudflare DNS

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-dns:
    runs-on: ubuntu-latest
    container: python:3.10-slim
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create .env file from secrets
      run: |
        cat > .env << EOF
        CF1=${{ secrets.CF1 }}
        CF2=${{ secrets.CF2 }}
        INCLUDE_LINES=${{ secrets.INCLUDE_LINES }}
        CLOUDFLARE_ENABLE=${{ secrets.CLOUDFLARE_ENABLE }}
        CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ZONE_ID=${{ secrets.CLOUDFLARE_ZONE_ID }}
        CLOUDFLARE_DOMAIN=${{ secrets.CLOUDFLARE_DOMAIN }}
        USER_AGENT=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36
        TIMEOUT=30
        EOF
        
    - name: Install dependencies
      run: pip install requests beautifulsoup4 python-dotenv
        
    - name: Run main script
      run: python get_ip.py
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: cf-ip-results
        path: output/
        retention-days: 7
